enableEmoji = true
enableRobotsTXT = true
disqusShortname = "pitlords"
languageCode = "en-us"
title = "Pitlord Inc."
baseURL = "https://pitlords.com"
googleAnalytics = ""
paginate = 9
summaryLength = "10"

[permalinks]
blogs = "/blog/:slug/"
products = "/products/:slug/"
pages = "/:slug"

[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = false

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true

[author]
homepage = "https://github.com/goldcoders"
name = "Pitlord"
avatar = "/images/avatar.svg"

[build]
noJSConfigInAssets = false
useResourceCacheWhen = "fallback"
writeStats = true
